//! Verbatim seasonal insect spawn tables extracted from
//! `src/actor/ac_set_ovl_insect.c` (GAFE01_00 Rev. 0).
//! Do not edit by hand; regenerate with /tmp/extract_species.py.

use super::species::{InsectArea, InsectSpawnEntry, InsectType};

pub static INSECT_TBL_L_INSECT_M_OTHER_T: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 15 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 15 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M3_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M4_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M4_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M4_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 25 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 24 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 12 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 12 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M4_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M4_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M4_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 20 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 20 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 13 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 12 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 12 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 1 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 15 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 2 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M5_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 1 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Firefly, area: InsectArea::FlyingNearWater, weight: 20 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 15 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 15 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 21 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 8 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 25 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 10 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M6_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Firefly, area: InsectArea::FlyingNearWater, weight: 76 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 7 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::RobustCicada, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::WalkerCicada, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 6 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 4 },
    InsectSpawnEntry { insect: InsectType::JewelBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::CommonDragonfly, area: InsectArea::Flying, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 8 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 7 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 15 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 8 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 20 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M7_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 15 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 15 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 2 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::RobustCicada, area: InsectArea::OnTree, weight: 4 },
    InsectSpawnEntry { insect: InsectType::WalkerCicada, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 4 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Grasshopper, area: InsectArea::InBush, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 4 },
    InsectSpawnEntry { insect: InsectType::JewelBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 8 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 9 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Grasshopper, area: InsectArea::InBush, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 9 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 14 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 20 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M8_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 15 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 43 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 15 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 27 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 20 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::WalkerCicada, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 19 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 19 },
    InsectSpawnEntry { insect: InsectType::Grasshopper, area: InsectArea::InBush, weight: 11 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 14 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 50 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Grasshopper, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 20 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PondSkater, area: InsectArea::OnWater, weight: 5 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M9_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 40 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 15 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 28 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Spider, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 4 },
];
pub static INSECT_TBL_L_INSECT_M10_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 30 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 20 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M10_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M10_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 3 },
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 15 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 15 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M10_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 54 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M10_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::RedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M10_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 30 },
    InsectSpawnEntry { insect: InsectType::BellCricket, area: InsectArea::InBush, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PineCricket, area: InsectArea::InBush, weight: 20 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::LongLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MigratoryLocust, area: InsectArea::OnGround, weight: 5 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_M11_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::Cricket, area: InsectArea::InBush, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnFlower, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Cockroach, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::PillBug, area: InsectArea::UnderRock, weight: 5 },
    InsectSpawnEntry { insect: InsectType::MoleCricket, area: InsectArea::Underground, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Bagworm, area: InsectArea::OnTree, weight: 2 },
];
pub static INSECT_TBL_L_INSECT_ISL_T1: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 6 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 78 },
];
pub static INSECT_TBL_L_INSECT_ISL_T2: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 30 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::GiantBeetle, area: InsectArea::OnTree, weight: 1 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 48 },
];
pub static INSECT_TBL_L_INSECT_ISL_T3: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 8 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 8 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 6 },
    InsectSpawnEntry { insect: InsectType::RobustCicada, area: InsectArea::OnTree, weight: 10 },
    InsectSpawnEntry { insect: InsectType::WalkerCicada, area: InsectArea::OnTree, weight: 8 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 18 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::JewelBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 7 },
];
pub static INSECT_TBL_L_INSECT_ISL_T4: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::CommonButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 8 },
    InsectSpawnEntry { insect: InsectType::YellowButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 8 },
    InsectSpawnEntry { insect: InsectType::TigerButterfly, area: InsectArea::FlyingNearFlowersOrAround, weight: 10 },
    InsectSpawnEntry { insect: InsectType::PurpleButterfly, area: InsectArea::OnTree, weight: 5 },
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 27 },
    InsectSpawnEntry { insect: InsectType::BrownCicada, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::DarnerDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::BandedDragonfly, area: InsectArea::Flying, weight: 5 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 6 },
    InsectSpawnEntry { insect: InsectType::LonghornBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::Ladybug, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::SpottedLadybug, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Mantis, area: InsectArea::OnFlower, weight: 4 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 5 },
];
pub static INSECT_TBL_L_INSECT_ISL_T5: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::EveningCicada, area: InsectArea::OnTree, weight: 42 },
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 8 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 10 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 37 },
];
pub static INSECT_TBL_L_INSECT_ISL_T6: &[InsectSpawnEntry] = &[
    InsectSpawnEntry { insect: InsectType::DroneBeetle, area: InsectArea::OnTree, weight: 8 },
    InsectSpawnEntry { insect: InsectType::DynastidBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::FlatStagBeetle, area: InsectArea::OnTree, weight: 3 },
    InsectSpawnEntry { insect: InsectType::SawStagBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::MountainBeetle, area: InsectArea::OnTree, weight: 2 },
    InsectSpawnEntry { insect: InsectType::Mosquito, area: InsectArea::Flying, weight: 7 },
    InsectSpawnEntry { insect: InsectType::Snail, area: InsectArea::RainingOnFlower, weight: 3 },
    InsectSpawnEntry { insect: InsectType::None, area: InsectArea::Nothing, weight: 72 },
];
/// Town insect tables: [month 0-11][time term 0-5].
pub static INSECT_TOWN: [[&[InsectSpawnEntry]; 6]; 12] = [
    [
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
    ],
    [
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
    ],
    [
        INSECT_TBL_L_INSECT_M3_T1,
        INSECT_TBL_L_INSECT_M3_T2,
        INSECT_TBL_L_INSECT_M3_T3,
        INSECT_TBL_L_INSECT_M3_T4,
        INSECT_TBL_L_INSECT_M3_T5,
        INSECT_TBL_L_INSECT_M3_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M4_T1,
        INSECT_TBL_L_INSECT_M4_T2,
        INSECT_TBL_L_INSECT_M4_T3,
        INSECT_TBL_L_INSECT_M4_T4,
        INSECT_TBL_L_INSECT_M4_T5,
        INSECT_TBL_L_INSECT_M4_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M5_T1,
        INSECT_TBL_L_INSECT_M5_T2,
        INSECT_TBL_L_INSECT_M5_T3,
        INSECT_TBL_L_INSECT_M5_T4,
        INSECT_TBL_L_INSECT_M5_T5,
        INSECT_TBL_L_INSECT_M5_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M6_T1,
        INSECT_TBL_L_INSECT_M6_T2,
        INSECT_TBL_L_INSECT_M6_T3,
        INSECT_TBL_L_INSECT_M6_T4,
        INSECT_TBL_L_INSECT_M6_T5,
        INSECT_TBL_L_INSECT_M6_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M7_T1,
        INSECT_TBL_L_INSECT_M7_T2,
        INSECT_TBL_L_INSECT_M7_T3,
        INSECT_TBL_L_INSECT_M7_T4,
        INSECT_TBL_L_INSECT_M7_T5,
        INSECT_TBL_L_INSECT_M7_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M8_T1,
        INSECT_TBL_L_INSECT_M8_T2,
        INSECT_TBL_L_INSECT_M8_T3,
        INSECT_TBL_L_INSECT_M8_T4,
        INSECT_TBL_L_INSECT_M8_T5,
        INSECT_TBL_L_INSECT_M8_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M9_T1,
        INSECT_TBL_L_INSECT_M9_T2,
        INSECT_TBL_L_INSECT_M9_T3,
        INSECT_TBL_L_INSECT_M9_T4,
        INSECT_TBL_L_INSECT_M9_T5,
        INSECT_TBL_L_INSECT_M9_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M10_T1,
        INSECT_TBL_L_INSECT_M10_T2,
        INSECT_TBL_L_INSECT_M10_T3,
        INSECT_TBL_L_INSECT_M10_T4,
        INSECT_TBL_L_INSECT_M10_T5,
        INSECT_TBL_L_INSECT_M10_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M11_T1,
        INSECT_TBL_L_INSECT_M11_T2,
        INSECT_TBL_L_INSECT_M11_T3,
        INSECT_TBL_L_INSECT_M11_T4,
        INSECT_TBL_L_INSECT_M11_T5,
        INSECT_TBL_L_INSECT_M11_T6,
    ],
    [
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
        INSECT_TBL_L_INSECT_M_OTHER_T,
    ],
];

/// Island insect tables: [time term 0-5].
pub static INSECT_ISLAND: [&[InsectSpawnEntry]; 6] = [
    INSECT_TBL_L_INSECT_ISL_T1,
    INSECT_TBL_L_INSECT_ISL_T2,
    INSECT_TBL_L_INSECT_ISL_T3,
    INSECT_TBL_L_INSECT_ISL_T4,
    INSECT_TBL_L_INSECT_ISL_T5,
    INSECT_TBL_L_INSECT_ISL_T6,
];

/// Multi-birth table `l_insect_birth_sum`: (min_birth_count, additional_range)
/// in `aINS_INSECT_TYPE_*` order.
pub static INSECT_BIRTH_SUM: [(u8, u8); 42] = [
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (6, 3),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (6, 3),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (1, 0),
    (0, 0),
];
