//! NPC AI beyond movement: schedules, daily routines, reactions.
//!
//! Verified against `m_npc_schedule.c`, `ac_npc_schedule*.c_inc`,
//! `ac_npc_think.c_inc`, `ac_npc_think_wander.c_inc`,
//! `ac_npc_think_sleep.c_inc`, `ac_npc_act_greeting.c_inc`,
//! `m_npc.c` (USA Rev. 0 decomp).
//!
//! Architecture: the daily schedule only establishes broad behavioral
//! context (FIELD / IN_HOUSE / SLEEP). Inside that state, behavior is
//! generated by an interrupt-driven think/action system —
//! "interrupt before decision", not a behavior tree.
//!
//! Corrections to the research brief worth recording here:
//! - The talk-throttle temperament table is keyed by **looks** (personality),
//!   not mood: `mNpc_TalkEndMove` is called with `animal->id.looks` and the
//!   table guard checks `looks < mNpc_LOOKS_NUM`. The header's parameter is
//!   misleadingly named `feel`, and the source comments say
//!   `// mNpc_FEEL_NORMAL` etc., but the code path is unambiguous.
//! - The brief swapped the last two temperament columns. The struct is
//!   `{unlock_timer, over_impatient_num, talk_num_max}`: NORMAL is
//!   unlock=4000, over-impatient=12, max-talks=15 (not max 12 / impatient 15).
//! - Umbrella control runs unconditionally before the interrupt chain; it is
//!   not a checked member of the priority else-chain.

/// `mNPS_SCHED_*` (m_npc_schedule_h.h).
pub mod sched {
    pub const FIELD: u32 = 0;
    pub const IN_HOUSE: u32 = 1;
    pub const SLEEP: u32 = 2;
    pub const STAND: u32 = 3;
    pub const WANDER: u32 = 4;
    pub const WALK_WANDER: u32 = 5;
    pub const SPECIAL: u32 = 6;
}

/// Six hard-coded daily schedule tables, indexed by looks
/// (girl, ko_girl, boy, sport_man, grim_man, naniwa_lady).
/// Entries are (schedule type, end time as (hour, min, sec)); the
/// manager walks until `end_time > now_sec` and takes that entry's type.
pub const SCHEDULE_TABLES: [[[u32; 3]; 9]; 6] = [
    // Girl
    [
        [sched::SLEEP, 5, 0], [sched::IN_HOUSE, 6, 0], [sched::FIELD, 12, 0],
        [sched::IN_HOUSE, 13, 0], [sched::FIELD, 18, 30], [sched::IN_HOUSE, 21, 0],
        [sched::SLEEP, 24, 0], [u32::MAX, u32::MAX, u32::MAX], [u32::MAX, u32::MAX, u32::MAX],
    ],
    // Ko-girl
    [
        [sched::SLEEP, 7, 0], [sched::IN_HOUSE, 8, 0], [sched::FIELD, 13, 0],
        [sched::IN_HOUSE, 14, 0], [sched::FIELD, 22, 0], [sched::IN_HOUSE, 23, 30],
        [sched::SLEEP, 24, 0], [u32::MAX, u32::MAX, u32::MAX], [u32::MAX, u32::MAX, u32::MAX],
    ],
    // Boy
    [
        [sched::SLEEP, 8, 0], [sched::IN_HOUSE, 9, 0], [sched::FIELD, 12, 0],
        [sched::IN_HOUSE, 14, 0], [sched::FIELD, 19, 30], [sched::IN_HOUSE, 22, 0],
        [sched::SLEEP, 24, 0], [u32::MAX, u32::MAX, u32::MAX], [u32::MAX, u32::MAX, u32::MAX],
    ],
    // Sport-man (crosses midnight)
    [
        [sched::IN_HOUSE, 1, 0], [sched::SLEEP, 5, 30], [sched::IN_HOUSE, 6, 30],
        [sched::FIELD, 12, 0], [sched::IN_HOUSE, 12, 30], [sched::FIELD, 23, 0],
        [sched::IN_HOUSE, 24, 0], [u32::MAX, u32::MAX, u32::MAX], [u32::MAX, u32::MAX, u32::MAX],
    ],
    // Grim-man
    [
        [sched::FIELD, 4, 0], [sched::IN_HOUSE, 5, 0], [sched::SLEEP, 10, 0],
        [sched::IN_HOUSE, 11, 0], [sched::FIELD, 15, 0], [sched::IN_HOUSE, 16, 0],
        [sched::FIELD, 22, 0], [sched::IN_HOUSE, 23, 0], [sched::FIELD, 24, 0],
    ],
    // Naniwa lady
    [
        [sched::FIELD, 1, 30], [sched::IN_HOUSE, 2, 30], [sched::SLEEP, 9, 0],
        [sched::IN_HOUSE, 10, 0], [sched::FIELD, 13, 0], [sched::IN_HOUSE, 14, 0],
        [sched::FIELD, 21, 0], [sched::IN_HOUSE, 22, 0], [sched::FIELD, 24, 0],
    ],
];

fn end_time_sec(entry: &[u32; 3]) -> u32 {
    entry[1] * 3600 + entry[2] * 60
}

/// `mNPS_schedule_manager_sub` verbatim: walk the table until
/// `end_time > now_sec`; `saved_type` = entry type; if
/// `forced_timer > 0`, `current_type = forced_type` and the timer
/// decrements by `forced_ticks`, else `current_type = saved_type`.
/// Returns (saved_type, current_type, new forced_timer).
pub fn schedule_manager_sub(
    looks: usize,
    now_sec: u32,
    forced_type: u32,
    forced_timer: i32,
    forced_ticks: i32,
) -> (u32, u32, i32) {
    let table = &SCHEDULE_TABLES[looks.min(5)];
    let mut saved = table[table.len() - 1][0];
    for entry in table.iter() {
        if entry[0] == u32::MAX {
            break;
        }
        if end_time_sec(entry) > now_sec {
            saved = entry[0];
            break;
        }
    }
    let mut timer = forced_timer;
    let current = if timer > 0 {
        timer -= forced_ticks;
        if timer < 0 {
            timer = 0;
        }
        forced_type
    } else {
        saved
    };
    (saved, current, timer)
}

/// Global override: First Job in progress or Halloween active forces
/// every town animal to FIELD (`mNPS_schedule_manager_sub0`).
pub fn global_schedule_override(first_job: bool, halloween_active: bool) -> Option<u32> {
    if first_job || halloween_active {
        Some(sched::FIELD)
    } else {
        None
    }
}

/// `aNPC_check_chg_schedule` verbatim: switch allowed only when the
/// NPC's step matches, the desired type differs from current_type,
/// and the NPC is not talking.
pub fn check_chg_schedule(step: u8, npc_step: u8, npc_type: u32, current_type: u32, talking: bool) -> bool {
    npc_step == step && npc_type != current_type && !talking
}

/// FIELD schedule steps.
pub mod field_step {
    pub const LEAVE_HOUSE: u8 = 0;
    pub const WANDER: u8 = 1;
    pub const IN_BLOCK: u8 = 2;
    pub const PITFALL: u8 = 3;
}

/// Sleep forced-schedule: a sleeping NPC interrupted (talk/umbrella)
/// forces itself to FIELD (or IN_HOUSE if in its home block) for
/// 7200 frames ≈ 2 minutes.
pub const SLEEP_FORCE_SCHEDULE_FRAMES: i32 = 7200;

pub fn sleep_force_schedule_type(in_home_block: bool) -> u32 {
    if in_home_block {
        sched::IN_HOUSE
    } else {
        sched::FIELD
    }
}

/// Interrupt dispatcher members, in the source's checked order.
/// Umbrella control runs unconditionally before the chain; friendship
/// is evaluated last.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Interrupt {
    TalkStart,
    Pitfall,
    RightHand,
    LeftHand,
    Uzai,
    Entrance,
    Clap,
    Fatigue,
    CollisionTurn,
    Obstacle,
    Ball,
    InsectGyoei,
    Friendship,
}

/// `aNPC_think_chk_interrupt_proc` order, verbatim.
/// The `moving` split: the clap/fatigue/turn/obstacle/ball/
 /// insect chain only runs while speed != 0; when still, only clap is
/// checked before friendship.
pub fn interrupt_order(moving: bool) -> &'static [Interrupt] {
    use Interrupt::*;
    if moving {
        &[
            TalkStart, Pitfall, RightHand, LeftHand, Uzai, Entrance, Clap, Fatigue, CollisionTurn,
            Obstacle, Ball, InsectGyoei, Friendship,
        ]
    } else {
        &[TalkStart, Pitfall, RightHand, LeftHand, Uzai, Entrance, Clap, Friendship]
    }
}

/// Wander decision borders per looks: `{border0, border1}` —
/// `rng(10) <= border0` → WAIT, `<= border1` → WALK, else RUN.
/// (Source comments give the percentages; the borders are verbatim.)
pub const WANDER_BORDERS: [[i32; 2]; 7] = [
    [3, 6], // girl: 40% wait, 30% walk, 30% run
    [6, 8], // ko-girl: 70/20/10
    [5, 7], // boy: 60/20/20
    [2, 4], // sport-man: 30/20/50
    [3, 6], // grim-man: 40/30/30
    [4, 8], // naniwa-lady: 50/40/10
    [4, 8], // special NPCs: 50/40/10
];

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WanderAct {
    Wait,
    Walk,
    Run,
}

/// `aNPC_think_wander_decide_next` verbatim:
/// fatigue OR SLEEPY feel → WAIT (personality table skipped);
/// WALK_WANDER think → `rng > 5` ? WAIT : WALK;
/// else the border table; a RUN pick is downgraded to WALK when the
/// schedule is forced into FIELD (`current==FIELD != saved`).
pub fn wander_decide_next(
    looks: usize,
    rng10: i32,
    fatigued: bool,
    feel_sleepy: bool,
    think_walk_wander: bool,
    is_special_npc: bool,
    sched_current: u32,
    sched_saved: u32,
) -> WanderAct {
    if fatigued || feel_sleepy {
        return WanderAct::Wait;
    }
    let act = if think_walk_wander {
        if rng10 > 5 {
            WanderAct::Wait
        } else {
            WanderAct::Walk
        }
    } else {
        let borders = if is_special_npc {
            &WANDER_BORDERS[6]
        } else {
            &WANDER_BORDERS[looks.min(5)]
        };
        if rng10 <= borders[0] {
            WanderAct::Wait
        } else if rng10 <= borders[1] {
            WanderAct::Walk
        } else {
            WanderAct::Run
        }
    };
    if act == WanderAct::Run && sched_current == sched::FIELD && sched_current != sched_saved {
        WanderAct::Walk
    } else {
        act
    }
}

/// Uzai (annoyance) thresholds: `max_uzai_cross = {600, 240}`,
/// `max_uzai_tool = {3, 1}`, both indexed by `cross == 1`.
/// Returns TRUE when the reaction triggers.
pub fn uzai_trigger(step: i32, tool: i32, crossed: bool) -> bool {
    let idx = crossed as usize;
    let max_cross = [600, 240][idx];
    let max_tool = [3, 1][idx];
    step > max_cross || tool == max_tool
}

/// Talk-throttle temperament table, keyed by LOOKS (personality), NOT
/// mood: `{unlock_timer, over_impatient_num, talk_num_max}`.
pub const TALK_TEMPER: [(u16, u8, u8); 6] = [
    (4000, 12, 15),
    (3000, 10, 13),
    (4000, 12, 15),
    (4000, 10, 13),
    (5000, 9, 12),
    (5000, 9, 12),
];

/// `mNpc_TalkEndMove` verbatim: sets the 1000-frame talk timer; while
/// the timer is active and talk_num < talk_num_max, talk_num++;
/// when talk_num reaches over_impatient_num, the unlock timers are
/// (re)set from the temperament table.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct TalkThrottle {
    pub timer: u16,
    pub talk_num: u8,
    pub unlock_timer: u16,
    pub reset_timer: u16,
}

impl TalkThrottle {
    pub fn new() -> Self {
        TalkThrottle {
            timer: 0,
            talk_num: 0,
            unlock_timer: 0,
            reset_timer: 0,
        }
    }

    pub fn talk_end(&mut self, looks: usize) {
        let (unlock_timer, over_impatient_num, talk_num_max) = TALK_TEMPER[looks.min(5)];
        self.timer = 1000;
        if self.talk_num < talk_num_max && self.timer > 0 {
            self.talk_num += 1;
        }
        if self.talk_num >= over_impatient_num {
            self.unlock_timer = unlock_timer;
            self.reset_timer = unlock_timer;
        }
    }

    /// `mNpc_GetOverImpatient`: NORMAL < impatient, MILDLY_ANNOYED <
    /// impatient-but-below-max, ANNOYED >= max (refuses to talk).
    pub fn patience(&self, looks: usize) -> Patience {
        let (_, over_impatient_num, talk_num_max) = TALK_TEMPER[looks.min(5)];
        if self.talk_num >= talk_num_max {
            Patience::Annoyed
        } else if self.talk_num >= over_impatient_num {
            Patience::MildlyAnnoyed
        } else {
            Patience::Normal
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Patience {
    Normal,
    MildlyAnnoyed,
    Annoyed,
}

/// NPC-NPC greeting effects (`ac_npc_act_greeting.c_inc`): both
/// participants get relation +8 toward each other and feel HAPPY.
pub const GREETING_RELATION_BUMP: i32 = 8;

// ---- C ABI ----

/// C ABI: `mNPS_schedule_manager_sub` for looks at `now_sec`.
/// Packs (saved_type, current_type, forced_timer).
#[no_mangle]
pub extern "C" fn pc_schedule_step(
    looks: u8,
    now_sec: u32,
    forced_type: u32,
    forced_timer: i32,
    forced_ticks: i32,
    out: *mut u32,
) {
    if out.is_null() {
        return;
    }
    let (saved, current, timer) =
        schedule_manager_sub(looks as usize, now_sec, forced_type, forced_timer, forced_ticks);
    unsafe {
        *out.add(0) = saved;
        *out.add(1) = current;
        *out.add(2) = timer as u32;
    }
}

/// C ABI: global event override; returns 1 and writes FIELD when
/// active, else 0.
#[no_mangle]
pub extern "C" fn pc_schedule_global_override(first_job: u8, halloween: u8, out_type: *mut u32) -> u8 {
    match global_schedule_override(first_job != 0, halloween != 0) {
        Some(t) => {
            if !out_type.is_null() {
                unsafe {
                    *out_type = t;
                }
            }
            1
        }
        None => 0,
    }
}

/// C ABI: `aNPC_think_wander_decide_next`; 0=Wait, 1=Walk, 2=Run.
#[no_mangle]
pub extern "C" fn pc_wander_decide_next(
    looks: u8,
    rng10: i32,
    fatigued: u8,
    feel_sleepy: u8,
    think_walk_wander: u8,
    is_special_npc: u8,
    sched_current: u32,
    sched_saved: u32,
) -> u8 {
    match wander_decide_next(
        looks as usize,
        rng10,
        fatigued != 0,
        feel_sleepy != 0,
        think_walk_wander != 0,
        is_special_npc != 0,
        sched_current,
        sched_saved,
    ) {
        WanderAct::Wait => 0,
        WanderAct::Walk => 1,
        WanderAct::Run => 2,
    }
}

/// C ABI: uzai trigger check.
#[no_mangle]
pub extern "C" fn pc_uzai_trigger(step: i32, tool: i32, crossed: u8) -> u8 {
    uzai_trigger(step, tool, crossed != 0) as u8
}

/// C ABI: talk-throttle patience; 0=Normal, 1=MildlyAnnoyed, 2=Annoyed.
#[no_mangle]
pub extern "C" fn pc_talk_patience(looks: u8, talk_num: u8) -> u8 {
    let t = TalkThrottle {
        timer: 0,
        talk_num,
        unlock_timer: 0,
        reset_timer: 0,
    };
    match t.patience(looks as usize) {
        Patience::Normal => 0,
        Patience::MildlyAnnoyed => 1,
        Patience::Annoyed => 2,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schedule_tables_and_manager() {
        // Girl at 07:00 -> the (12,0,0) FIELD entry is the first with end > now.
        let (saved, current, timer) = schedule_manager_sub(0, 7 * 3600, 0, 0, 1);
        assert_eq!((saved, current, timer), (sched::FIELD, sched::FIELD, 0));
        // Girl at 04:00 -> SLEEP (end 05:00).
        let (saved, _, _) = schedule_manager_sub(0, 4 * 3600, 0, 0, 1);
        assert_eq!(saved, sched::SLEEP);
        // Forced timer overrides and decrements.
        let (saved, current, timer) =
            schedule_manager_sub(0, 7 * 3600, sched::IN_HOUSE, 100, 3);
        assert_eq!((saved, current, timer), (sched::FIELD, sched::IN_HOUSE, 97));
        // Timer clamps at 0.
        let (_, _, timer) = schedule_manager_sub(0, 7 * 3600, sched::IN_HOUSE, 2, 5);
        assert_eq!(timer, 0);
        // Global override.
        assert_eq!(global_schedule_override(true, false), Some(sched::FIELD));
        assert_eq!(global_schedule_override(false, true), Some(sched::FIELD));
        assert_eq!(global_schedule_override(false, false), None);
        // Schedule change gate: needs step match, type change, not talking.
        assert!(check_chg_schedule(1, 1, sched::IN_HOUSE, sched::FIELD, false));
        assert!(!check_chg_schedule(1, 2, sched::IN_HOUSE, sched::FIELD, false));
        assert!(!check_chg_schedule(1, 1, sched::FIELD, sched::FIELD, false));
        assert!(!check_chg_schedule(1, 1, sched::IN_HOUSE, sched::FIELD, true));
        // Sleep force schedule.
        assert_eq!(sleep_force_schedule_type(true), sched::IN_HOUSE);
        assert_eq!(sleep_force_schedule_type(false), sched::FIELD);
        assert_eq!(SLEEP_FORCE_SCHEDULE_FRAMES, 7200);
        // C ABI.
        let mut out = [0u32; 3];
        pc_schedule_step(0, 7 * 3600, 0, 0, 1, out.as_mut_ptr());
        assert_eq!(out, [sched::FIELD, sched::FIELD, 0]);
        let mut t = 0u32;
        assert_eq!(pc_schedule_global_override(1, 0, &mut t), 1);
        assert_eq!(t, sched::FIELD);
        assert_eq!(pc_schedule_global_override(0, 0, &mut t), 0);
    }

    #[test]
    fn wander_and_interrupt() {
        // Border tables: girl {3,6}: rng 0-3 wait, 4-6 walk, 7-9 run.
        assert_eq!(wander_decide_next(0, 3, false, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Wait);
        assert_eq!(wander_decide_next(0, 6, false, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Walk);
        assert_eq!(wander_decide_next(0, 7, false, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Run);
        // ko-girl {6,8}: 9 -> run.
        assert_eq!(wander_decide_next(1, 9, false, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Run);
        assert_eq!(wander_decide_next(1, 7, false, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Walk);
        // Fatigue or sleepy -> wait regardless of rng.
        assert_eq!(wander_decide_next(3, 9, true, false, false, false, sched::FIELD, sched::FIELD), WanderAct::Wait);
        assert_eq!(wander_decide_next(3, 9, false, true, false, false, sched::FIELD, sched::FIELD), WanderAct::Wait);
        // WALK_WANDER think: rng>5 wait else walk.
        assert_eq!(wander_decide_next(0, 6, false, false, true, false, sched::FIELD, sched::FIELD), WanderAct::Wait);
        assert_eq!(wander_decide_next(0, 5, false, false, true, false, sched::FIELD, sched::FIELD), WanderAct::Walk);
        // Forced FIELD (current != saved) downgrades run to walk.
        assert_eq!(wander_decide_next(0, 9, false, false, false, false, sched::FIELD, sched::IN_HOUSE), WanderAct::Walk);
        // Interrupt order: friendship last.
        let ord = interrupt_order(true);
        assert_eq!(ord[0], Interrupt::TalkStart);
        assert_eq!(*ord.last().unwrap(), Interrupt::Friendship);
        let ord_still = interrupt_order(false);
        assert!(ord_still.contains(&Interrupt::Clap));
        assert!(!ord_still.contains(&Interrupt::Ball));
        // Uzai thresholds.
        assert!(uzai_trigger(601, 0, false));
        assert!(!uzai_trigger(600, 0, false));
        assert!(uzai_trigger(0, 3, false));
        assert!(uzai_trigger(241, 0, true));
        assert!(uzai_trigger(0, 1, true));
        // Talk throttle: NORMAL looks=0: over-impatient at 12, annoyed at 15.
        let mut t = TalkThrottle::new();
        for _ in 0..11 {
            t.talk_end(0);
        }
        assert_eq!(t.patience(0), Patience::Normal);
        t.talk_end(0);
        assert_eq!(t.patience(0), Patience::MildlyAnnoyed);
        for _ in 0..3 {
            t.talk_end(0);
        }
        assert_eq!(t.patience(0), Patience::Annoyed);
        assert_eq!(t.timer, 1000);
        // C ABI.
        assert_eq!(pc_wander_decide_next(0, 7, 0, 0, 0, 0, sched::FIELD, sched::FIELD), 2);
        assert_eq!(pc_wander_decide_next(0, 9, 0, 0, 0, 0, sched::FIELD, sched::IN_HOUSE), 1);
        assert_eq!(pc_uzai_trigger(601, 0, 0), 1);
        assert_eq!(pc_talk_patience(0, 12), 1);
        assert_eq!(pc_talk_patience(0, 15), 2);
        assert_eq!(pc_talk_patience(0, 5), 0);
    }
}
