//! Request-selection caller for the Rust rewrite.
//!
//! Source-verified (upstream `src/actor/ac_quest_talk_normal_init.c`,
//! `src/actor/ac_quest_talk_island.c`):
//!
//! This is the junction the earlier research was missing. The quest
//! talk manager for normal villagers binds player-possession state to
//! dialogue and trade offers:
//!
//! 1. `aQMgr_decide_msg_check_possession(check_proc, base_msg,
//!    item_idx, msg_count, cancel_item)`: calls a possession-check
//!    function; if it finds a pocket (`idx != -1`), picks a random
//!    message variant `base_msg + mQst_GetRandom(msg_count)` from a
//!    per-personality table (`l_ki_ftr[looks]`, `l_trade_ftr[looks]`,
//!    six personalities) and records the pocket index. Returns -1 when
//!    the player lacks the item, so that dialogue option fails.
//!
//! 2. `aQMgr_get_possession_ftr_cpt_wl_rnd` — the actual "impulse
//!    buying" selector: counts eligible carried furniture (FTR0/FTR1
//!    foreground types plus carpets and walls, NORMAL condition,
//!    excluding the cancel item) with the Sum query variants, then
//!    `sel_idx = RANDOM(item_cnt)` and walks the pockets, taking the
//!    sel_idx-th eligible item. Selection is uniform over *eligible
//!    carried items*, not over pockets and not first-match.
//!
//! 3. `aQMgr_get_possession_item_rnd`: the same uniform-random scheme
//!    for carried insects/fish.
//!
//! 4. Deterministic first-match variants (`..._ftr_cpt_wl`,
//!    `..._item`) are used for the message-decide paths ("ki" request
//!    and trade message selection); the `_rnd` variants feed the trade
//!    offer construction.
//!
//! 5. Trade offers (`aQMgr_order_decide_trade_common`): the villager
//!    wants the player's randomly chosen carried furniture
//!    (`trade_items[0]`), plus category goods generated by
//!    `mQst_GetGoods_common` — which carries the verified 1/10
//!    villager-house-furniture branch. The offered item is then chosen
//!    at random from the category goods, or forced to a pitfall seed
//!    in pitfall mode.
//!
//! 6. Message dispatch itself is probability-table driven
//!    (`aQMgr_decide_idx_prob_table`): the trade set uses
//!    `{25, 25, 25, 25}` (`l_trade_prob`); the normal set uses
//!    `{49, 17, 17, 17}` (`l_normal_3_prob`).
//!
//! So the confirmed end-to-end chain is:
//!
//! ```text
//! possession check (player pockets)
//!        │
//!        ▼
//! aQMgr_decide_msg_check_possession ──► dialogue message + pocket idx
//!
//! uniform-random carried furniture ──► villager's wanted item
//!         │
//!         ▼
//! mQst_GetGoods_common ──► offered goods (10%: villager house furniture)
//! ```
//!
//! The exact item-type decode (`ITEM_IS_FTR`, `ITEM1_CAT_*`) stays in
//! the C item database; this module takes eligibility as input.

use crate::item_prefs::{goods_source_for_furniture, GoodsSource};

/// One eligible carried item.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CarriedItem {
    pub pocket_idx: usize,
    pub item: u16,
}

/// Uniform-random selection among eligible carried items
/// (`aQMgr_get_possession_ftr_cpt_wl_rnd`):
/// count eligible, `sel = rng % count`, walk pockets and take the
/// sel-th eligible one. Returns the pocket index and the item.
pub fn pick_random_eligible(
    pockets: &[u16],
    eligible: &[bool],
    rng_value: u32,
) -> Option<CarriedItem> {
    if pockets.len() != eligible.len() || pockets.is_empty() {
        return None;
    }
    let count = eligible.iter().filter(|&&e| e).count();
    if count == 0 || count > pockets.len() {
        return None;
    }
    let mut sel = (rng_value % count as u32) as usize;
    for (i, (&item, &e)) in pockets.iter().zip(eligible.iter()).enumerate() {
        if e {
            if sel == 0 {
                return Some(CarriedItem { pocket_idx: i, item });
            }
            sel -= 1;
        }
    }
    None
}

/// First-match possession check (`aQMgr_get_possession_ftr_cpt_wl` and
/// friends): the first eligible pocket, or `None`.
pub fn pick_first_eligible(pockets: &[u16], eligible: &[bool]) -> Option<CarriedItem> {
    pockets
        .iter()
        .zip(eligible.iter())
        .enumerate()
        .find(|(_, (&_, &e))| e)
        .map(|(i, (&item, _))| CarriedItem { pocket_idx: i, item })
}

/// Bind a possession result to dialogue
/// (`aQMgr_decide_msg_check_possession`): when the player has the
/// item, the message is `base_msg + rng % msg_count` and the pocket
/// index is recorded; otherwise the dialogue option fails (`None`).
pub fn decide_msg_check_possession(
    found: Option<CarriedItem>,
    base_msg: i32,
    msg_count: u32,
    rng_value: u32,
) -> Option<(i32, usize)> {
    let c = found?;
    let msg = base_msg + (rng_value % msg_count.max(1)) as i32;
    Some((msg, c.pocket_idx))
}

/// Weighted message dispatch (`aQMgr_decide_idx_prob_table`): pick the
/// first table entry whose cumulative weight exceeds the roll.
pub fn decide_idx_prob_table(probs: &[u8], roll: u32) -> Option<usize> {
    let total: u32 = probs.iter().map(|&p| p as u32).sum();
    if total == 0 {
        return None;
    }
    let mut r = roll % total;
    for (i, &p) in probs.iter().enumerate() {
        let w = p as u32;
        if r < w {
            return Some(i);
        }
        r -= w;
    }
    None
}

/// The trade message set's verbatim weights (`l_trade_prob`).
pub const TRADE_PROBS: [u8; 4] = [25, 25, 25, 25];
/// The normal-talk set's verbatim weights (`l_normal_3_prob`).
pub const NORMAL_3_PROBS: [u8; 4] = [49, 17, 17, 17];

/// How the villager's offered item is chosen
/// (`aQMgr_SEL_ITEM_MODE_*`).
#[repr(u8)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TradeItemMode {
    Random = 0,
    Pitfall = 1,
}

/// A constructed trade offer.
#[derive(Clone, Debug)]
pub struct TradeOffer {
    /// The player's item the villager wants (`trade_items[0]`).
    pub wanted: Option<CarriedItem>,
    /// Category goods generated via `mQst_GetGoods_common`.
    pub goods: [u16; 3],
    /// Which goods source each entry came from.
    pub goods_source: [GoodsSource; 3],
    /// The item actually offered (`trade_items[4]`).
    pub offered: u16,
}

/// Sentinel used for pitfall mode (`ITM_PITFALL`).
pub const PITFALL_ITEM: u16 = 0x2512;

/// Build a trade offer (`aQMgr_order_decide_trade_common_item`):
/// the villager wants the player's randomly chosen carried item;
/// each category slot is filled by the goods generator (with its 1/10
/// house-furniture branch); the offered item is a random category good
/// or a pitfall seed in pitfall mode.
pub fn build_trade_offer(
    wanted: Option<CarriedItem>,
    category_goods: [(u16, u32); 3],
    mode: TradeItemMode,
    rng_value: u32,
) -> TradeOffer {
    let mut goods = [0u16; 3];
    let mut goods_source = [GoodsSource::RandomItem; 3];
    for (i, &(item, roll_0_9)) in category_goods.iter().enumerate() {
        goods[i] = item;
        goods_source[i] = goods_source_for_furniture(roll_0_9);
    }
    let offered = match mode {
        TradeItemMode::Pitfall => PITFALL_ITEM,
        TradeItemMode::Random => goods[(rng_value as usize) % goods.len()],
    };
    TradeOffer { wanted, goods, goods_source, offered }
}

/// C ABI: uniform-random pick among eligible carried items; returns
/// the pocket index or -1. `eligible[i]` nonzero = pocket i eligible.
#[no_mangle]
pub extern "C" fn pc_request_pick_carried(
    pockets: *const u16,
    eligible: *const u8,
    count: usize,
    rng_value: u32,
) -> i32 {
    if pockets.is_null() || eligible.is_null() || count == 0 {
        return -1;
    }
    let p = unsafe { core::slice::from_raw_parts(pockets, count) };
    let e = unsafe { core::slice::from_raw_parts(eligible, count) };
    let elig: Vec<bool> = e.iter().map(|&b| b != 0).collect();
    pick_random_eligible(p, &elig, rng_value)
        .map(|c| c.pocket_idx as i32)
        .unwrap_or(-1)
}

/// C ABI: weighted message dispatch; returns the chosen index or -1.
#[no_mangle]
pub extern "C" fn pc_request_dispatch(probs: *const u8, n: usize, roll: u32) -> i32 {
    if probs.is_null() || n == 0 {
        return -1;
    }
    let p = unsafe { core::slice::from_raw_parts(probs, n) };
    decide_idx_prob_table(p, roll).map(|i| i as i32).unwrap_or(-1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uniform_pick_over_eligible_items() {
        let pockets = [10u16, 20, 30, 40, 50];
        let eligible = [false, true, false, true, true];
        // 3 eligible; rng 0 -> first eligible (pocket 1).
        assert_eq!(
            pick_random_eligible(&pockets, &eligible, 0),
            Some(CarriedItem { pocket_idx: 1, item: 20 })
        );
        // rng 2 -> third eligible (pocket 4).
        assert_eq!(
            pick_random_eligible(&pockets, &eligible, 2),
            Some(CarriedItem { pocket_idx: 4, item: 50 })
        );
        // rng 5 % 3 = 2 -> pocket 4 again.
        assert_eq!(
            pick_random_eligible(&pockets, &eligible, 5),
            Some(CarriedItem { pocket_idx: 4, item: 50 })
        );
        // No eligible -> None.
        assert_eq!(
            pick_random_eligible(&pockets, &[false; 5], 0),
            None
        );
    }

    #[test]
    fn first_match_pick() {
        let pockets = [10u16, 20, 30];
        let eligible = [false, true, true];
        assert_eq!(
            pick_first_eligible(&pockets, &eligible),
            Some(CarriedItem { pocket_idx: 1, item: 20 })
        );
        assert_eq!(pick_first_eligible(&pockets, &[false; 3]), None);
    }

    #[test]
    fn msg_binding() {
        let found = Some(CarriedItem { pocket_idx: 3, item: 77 });
        // base + rng%count.
        assert_eq!(decide_msg_check_possession(found, 1000, 3, 4), Some((1001, 3)));
        assert_eq!(decide_msg_check_possession(None, 1000, 3, 4), None);
    }

    #[test]
    fn prob_table_dispatch() {
        // {49,17,17,17}: roll 0 -> 0; roll 49 -> 1; roll 99 -> 3.
        assert_eq!(decide_idx_prob_table(&NORMAL_3_PROBS, 0), Some(0));
        assert_eq!(decide_idx_prob_table(&NORMAL_3_PROBS, 48), Some(0));
        assert_eq!(decide_idx_prob_table(&NORMAL_3_PROBS, 49), Some(1));
        assert_eq!(decide_idx_prob_table(&NORMAL_3_PROBS, 99), Some(3));
        // Equal 25s: roll 75 -> 3.
        assert_eq!(decide_idx_prob_table(&TRADE_PROBS, 75), Some(3));
        assert_eq!(decide_idx_prob_table(&[], 0), None);
    }

    #[test]
    fn trade_offer_modes() {
        let wanted = Some(CarriedItem { pocket_idx: 1, item: 55 });
        // roll 0 -> house furniture for slot 0.
        let offer = build_trade_offer(wanted, [(7, 0), (8, 5), (9, 9)], TradeItemMode::Random, 1);
        assert_eq!(offer.goods_source[0], GoodsSource::VillagerHouse);
        assert_eq!(offer.goods_source[1], GoodsSource::RandomItem);
        assert_eq!(offer.offered, 8);
        let pit = build_trade_offer(wanted, [(7, 0), (8, 5), (9, 9)], TradeItemMode::Pitfall, 0);
        assert_eq!(pit.offered, PITFALL_ITEM);
    }
}
